#ifndef SRC_INCLUDE_SE_CUSTOM_ATTR_H_
#define SRC_INCLUDE_SE_CUSTOM_ATTR_H_

#if ZCL_METERING_SUPPORT

#define ZCL_ATTRID_CUSTOM_ENERGY_PRESET     0xF000
#define ZCL_ATTRID_CUSTOM_DIVISOR_PRESET    0xF001
#define ZCL_ATTRID_CUSTOM_SERIAL_NUMBER     0xF002
#define ZCL_ATTRID_CUSTOM_NUMBER_DIGITS     0xF003
#define ZCL_ATTRID_CUSTOM_DEVICE_NAME       0xF004

#endif /* ZCL_METERING_SUPPORT */

#endif /* SRC_INCLUDE_SE_CUSTOM_ATTR_H_ */
